// <auto-generated />
using System;
using Application.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    partial class QuotesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Models.Quotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Альберт Эйнштейн",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Стремитесь не к успеху, а к ценностям, которые он дает."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Флоренс Найтингейл",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Своим успехом я обязана тому, что никогда не оправдывалась и не принимала оправданий от других."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Амелия Эрхарт",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Сложнее всего начать действовать, все остальное зависит только от упорства."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Федор Достоевский",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Надо любить жизнь больше, чем смысл жизни."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Альберт Эйнштейн",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Логика может привести Вас от пункта А к пункту Б, а воображение — куда угодно."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Борис Стругацкий",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Начинать всегда стоит с того, что сеет сомнения."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Вуди Аллен",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "80% успеха - это появиться в нужном месте в нужное время."
                        },
                        new
                        {
                            Id = 8,
                            Author = "Стив Джобс",
                            InsertDate = new DateTime(2021, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Text = "Ваше время ограничено, не тратьте его, живя чужой жизнью."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
